name: RL Workflow

on: 
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-3
  ECR_REPOSITORY: my_ecr_repository           
  ECS_SERVICE: my_ecs_service                 
  ECS_CLUSTER: my_ecs_cluster                 
  ECS_TASK_DEFINITION: ppo/app/task-definition.json

jobs:
  run_rl_agent:
    
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Set up Python environment
        run: |
          python3 -m venv venv
          source ./venv/bin/activate
      
      - name: Install dependencies
        run: |
          pip install -r ppo/requirements.txt
      
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd):$PYTHONPATH" >> $GITHUB_ENV

      #- name: Run script to collect and save dataset to S3
      #  run: |
      #    python ppo/app/src/resourceTuner.py  

      - name: Run script to train and save the model to S3
        run: |
          python ppo/app/src/predictor.py  

      - name: Run the PPO framework
        run: |
          python ppo/src/main.py






