name: RL Workflow

on: 
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-3
  ECR_REPOSITORY: my_ecr_repository           
  ECS_SERVICE: my_ecs_service                 
  ECS_CLUSTER: my_ecs_cluster                 
  ECS_TASK_DEFINITION: ppo/app/task-definition.json

  CONTAINER_NAME: my-app

jobs: 

      
  run_rl_agent:

    runs-on: ubuntu-latest
    environment: production
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      
      - name: Set up Python environment
        run: |
          python -m venv venv
          .venv/Scripts/activate
          python -m pip install --upgrade pip
          pip install -r ppo/requirements.txt
              
      - name: Run script to collect and save dataset to S3
        run: |
          cd ppo
          python app/src/resourceTuner.py  

      - name: Run script to train and save the model to S3
        run: |
          python ppo/app/src/predictor.py  

      - name: Run the PPO framework
        run: |
          python ppo/app/src/main.py


