name: RL Workflow

on: 
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-3
  ECR_REPOSITORY: my_ecr_repository           
  ECS_SERVICE: my_ecs_service                 
  ECS_CLUSTER: my_ecs_cluster                 
  ECS_TASK_DEFINITION: ppo/app/task-definition.json

jobs:
  build-sut-image:
    runs-on: ubuntu-latest
    environment: production
    outputs:
      output: ${{ steps.build-sut.outputs.sutimage }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push SUT image to Amazon ECR
        id: build-sut
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: sut
        run: |
          docker build -f ppo/app/src/sut/Dockerfile \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ppo/
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "sutimage=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV
          echo "sutimage=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
      
      - name: Use API image in ECS task definition
        run: |
          echo "SUT image: $sutimage"

  build-api-image:
    runs-on: ubuntu-latest
    environment: production
    outputs:
      output: ${{ steps.build-api.outputs.apiimage }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push API image to Amazon ECR
        id: build-api
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: api
        run: |
          docker build -f ppo/app/src/api/Dockerfile \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ppo/
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "apiimage=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV
          echo "apiimage=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
      
      - name: Use API image in ECS task definition
        run: |
          echo "API image: $apiimage"
          

  deploy-ecs:
    runs-on: ubuntu-latest
    environment: production
    needs: [build-sut-image, build-api-image] 
    env:
      PORT_SUT: 8001
      PORT_API: 8000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Echo sut and api images
        run: |
          echo "SUT image: ${{ needs.build-sut-image.outputs.* }} \ 
          API image: ${{ needs.build-api-image.outputs.* }}"

      - name: Update ECS task definition
        id: update-task-def
        run: |
          cp ${{ env.ECS_TASK_DEFINITION }} updated-task-definition.json

          jq --arg IMAGE "${{ needs.build-sut-image.outputs.output }}" \
             --argjson PORT ${{ env.PORT_SUT }} \
             '(.containerDefinitions[] | select(.name == "sut-container") | .image) = $IMAGE |
              (.containerDefinitions[] | select(.name == "sut-container") | .portMappings[0].containerPort) = $PORT |
              (.containerDefinitions[] | select(.name == "sut-container") | .portMappings[0].name) = "sut"' \
             updated-task-definition.json > updated-sut-task.json

          jq --arg IMAGE "${{ needs.build-api-image.outputs.output }}" \
             --argjson PORT ${{ env.PORT_API }} \
             '(.containerDefinitions[] | select(.name == "api-container") | .image) = $IMAGE |
              (.containerDefinitions[] | select(.name == "api-container") | .portMappings[0].containerPort) = $PORT |
              (.containerDefinitions[] | select(.name == "api-container") | .portMappings[0].name) = "api"' \
             updated-sut-task.json > final-task-definition.json

          # Output the final task definition for debugging
          cat final-task-definition.json

      - name: Deploy updated ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: final-task-definition.json
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true




